# Generated by Django 3.2.25 on 2025-08-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0005_corporate_is_verified'),
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpayment',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrgAuth.corporate'),
        ),
    ]
