# Generated by Django 3.2.25 on 2025-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_recordpayment_corporate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorpayment',
            old_name='reference_number',
            new_name='bill_number',
        ),
    ]
