# Generated by Django 3.2.25 on 2025-08-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0005_corporate_is_verified'),
        ('Payments', '0004_vendorpayment_corporate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrgAuth.corporateuser'),
        ),
    ]
