# Generated by Django 3.2.25 on 2025-09-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_auto_20250912_1310'),
        ('OrgAuth', '0008_alter_corporate_logo'),
        ('Payments', '0005_vendorpayment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='OrgAuth.corporateuser'),
        ),
        migrations.AddField(
            model_name='recordpayment',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordpayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='recordpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.account'),
        ),
        migrations.AlterField(
            model_name='recordpayment',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgAuth.corporate'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.account'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgAuth.corporate'),
        ),
    ]
