# Generated by Django 3.2.25 on 2025-11-06 14:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0008_alter_corporate_logo'),
        ('Payments', '0007_add_payment_gateway_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=6, default=Decimal('1.00'), max_digits=10)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_pdf_url', models.URLField(blank=True, null=True)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Organization Invoice',
                'verbose_name_plural': 'Organization Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=6, default=Decimal('1.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider', models.CharField(default='flutterwave', max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_pdf_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Organization Payment',
                'verbose_name_plural': 'Organization Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=6, default=Decimal('1.00'), max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('max_users', models.IntegerField(default=1)),
                ('current_users', models.IntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Organization Subscription',
                'verbose_name_plural': 'Organization Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='recordpayment',
            name='Payments_provider_ref_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordpayment',
            name='Payments_payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordpayment',
            name='Payments_corp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorpayment',
            name='Payments_vendor_provider_ref_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorpayment',
            name='Payments_vendor_payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorpayment',
            name='Payments_vendor_corp_date_idx',
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='provider_type',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='recordpayment',
            index=models.Index(fields=['provider_reference'], name='Payments_re_provide_48c73f_idx'),
        ),
        migrations.AddIndex(
            model_name='recordpayment',
            index=models.Index(fields=['payment_status'], name='Payments_re_payment_78139e_idx'),
        ),
        migrations.AddIndex(
            model_name='recordpayment',
            index=models.Index(fields=['corporate', 'payment_date'], name='Payments_re_corpora_a082e1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['provider_reference'], name='Payments_ve_provide_b26322_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['payment_status'], name='Payments_ve_payment_15837c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['corporate', 'payment_date'], name='Payments_ve_corpora_15daa5_idx'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='OrgAuth.corporate'),
        ),
        migrations.AddField(
            model_name='organizationpayment',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to='OrgAuth.corporate'),
        ),
        migrations.AddField(
            model_name='organizationpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Payments.organizationinvoice'),
        ),
        migrations.AddField(
            model_name='organizationinvoice',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='OrgAuth.corporate'),
        ),
        migrations.AddField(
            model_name='organizationinvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Payments.organizationsubscription'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['corporate', 'status'], name='Payments_or_corpora_4f6338_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status', 'end_date'], name='Payments_or_status_62e5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationpayment',
            index=models.Index(fields=['corporate', 'status'], name='Payments_or_corpora_28b510_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationpayment',
            index=models.Index(fields=['invoice', 'status'], name='Payments_or_invoice_b3d79e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationpayment',
            index=models.Index(fields=['provider_reference'], name='Payments_or_provide_8fcb08_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvoice',
            index=models.Index(fields=['corporate', 'status'], name='Payments_or_corpora_ecd6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvoice',
            index=models.Index(fields=['invoice_number'], name='Payments_or_invoice_34da9d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvoice',
            index=models.Index(fields=['due_date', 'status'], name='Payments_or_due_dat_926b02_idx'),
        ),
    ]
