# Generated by Django 3.2.25 on 2026-02-24 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0008_auto_20251106_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualSubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(default=dict)),
                ('max_transactions', models.IntegerField(default=100)),
                ('max_invoices', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'individual_subscription_plans',
                'ordering': ['monthly_price_kes'],
            },
        ),
        migrations.CreateModel(
            name='IndividualSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='Payments.individualsubscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'individual_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Payments.individualsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'individual_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='individualsubscription',
            index=models.Index(fields=['user', 'status'], name='individual__user_id_6a7a32_idx'),
        ),
        migrations.AddIndex(
            model_name='individualsubscription',
            index=models.Index(fields=['status', 'end_date'], name='individual__status_ccf756_idx'),
        ),
        migrations.AddIndex(
            model_name='individualpayment',
            index=models.Index(fields=['user', 'status'], name='individual__user_id_c99349_idx'),
        ),
        migrations.AddIndex(
            model_name='individualpayment',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='individual__mpesa_c_5b4d39_idx'),
        ),
        migrations.AddIndex(
            model_name='individualpayment',
            index=models.Index(fields=['idempotency_key'], name='individual__idempot_69368b_idx'),
        ),
        migrations.AddIndex(
            model_name='individualpayment',
            index=models.Index(fields=['status', 'created_at'], name='individual__status_8303d9_idx'),
        ),
    ]
