services:
  db:
    image: postgres:15
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d devdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quidpath_network
      

  redis:
    image: redis:alpine
    container_name: redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quidpath_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: "quidpath_backend.settings.dev"
      DJANGO_ENV: "dev"
      DEBUG: "true"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,*"
      DATABASE_URL: "postgresql://devuser:devpass@db:5432/devdb"
      SECRET_KEY: "local-secret-key"
      JWT_SECRET_KEY: "local-jwt-secret"
      SMTP_USER: "quidpath@gmail.com"
      SMTP_PASSWORD: "krpm whuy jfav lstb"
      MPESA_ENVIRONMENT: "production"
      MPESA_CONSUMER_KEY: "WZ6b1Y6ZjRbwNJwwQzULthXjesQR0OtsEuQh9jt7tz3CtSpG"
      MPESA_CONSUMER_SECRET: "zuVci1S1rl6An6bistz6jUo1eJ0Is8kM3IGlghGFCUpF4coKx7YtmGbAbLgvyddS"
      MPESA_BUSINESS_SHORT_CODE: "9895960"
      MPESA_TILL_NUMBER: "9100097"
      MPESA_PASSKEY: "bfb279f9aa9bdbcf158e97dd71a467cd"
      MPESA_CALLBACK_URL: "https://api.quidpath.com/api/payments/mpesa/callback/"
      BILLING_SERVICE_URL: "http://host.docker.internal:8002"
      BILLING_SERVICE_SECRET: "local-billing-secret"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      USE_MEMORY_CHANNEL_LAYER: "false"
    volumes:
      - .:/app
      - /app/.venv
      - media_dev:/app/media
      - staticfiles_dev:/app/staticfiles
    networks:
      - quidpath_network

networks:
  quidpath_network:
    driver: bridge

volumes:
  postgres_dev_data:
  redis_dev_data:
  media_dev:
  staticfiles_dev:
