services:
  db:
    image: postgres:15
    container_name: postgres_stage
    restart: unless-stopped
    volumes:
      - /mnt/quidpath-stage-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quidpath_network

  redis:
    image: redis:alpine
    container_name: redis_stage
    restart: unless-stopped
    volumes:
      - /mnt/quidpath-stage-data/redis:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quidpath_network

  backend:
    image: ${IMAGE_TAG}
    container_name: quidpath-backend-stage
    restart: unless-stopped
    ports:
      - "127.0.0.1:8011:8004"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      USE_MEMORY_CHANNEL_LAYER: ${USE_MEMORY_CHANNEL_LAYER}
      DJANGO_SETTINGS_MODULE: quidpath_backend.settings.stage
      ALLOWED_HOSTS: "stage-api.quidpath.com,stage.quidpath.com,localhost,127.0.0.1,0.0.0.0"
      CSRF_TRUSTED_ORIGINS: "https://stage.quidpath.com,https://stage-api.quidpath.com"
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      BILLING_SERVICE_URL: "http://billing-backend-stage:8000"
      BILLING_SERVICE_SECRET: ${BILLING_SERVICE_SECRET}
      BILLING_WEBHOOK_SECRET: ${BILLING_WEBHOOK_SECRET}

    volumes:
      - /mnt/quidpath-stage-data/media:/app/media
      - /mnt/quidpath-stage-data/staticfiles:/app/staticfiles
    networks:
      - quidpath_network

networks:
  quidpath_network:
    name: stage_quidpath_network
    driver: bridge