services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # mount local code for live reload
    env_file:
      - .env.dev
    environment:
      DJANGO_SETTINGS_MODULE: quidpath_backend.settings.dev
      BILLING_SERVICE_URL: http://billing-backend-dev:8000/api/billing  # Use container name for inter-service communication
    depends_on:
      - db
    networks:
      - backend_net   # 👈 attach to custom network
      - quidpath_network  # Shared network for billing service communication

  db:
        image: postgres:15
        container_name: postgres_dev
        restart: always
        environment:
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: devdb
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - backend_net

volumes:
  postgres_data:

networks:
  backend_net:
    driver: bridge
  quidpath_network:
    external: true  # Shared network for microservices communication
