# core/enums/choices.py
from django.db import models
class StatusChoices(models.TextChoices):
    ACTIVE = 'A', 'Active'
    INACTIVE = 'I', 'Inactive'
    PENDING = 'P', 'Pending'
    DELETED = 'D', 'Deleted'
    ARCHIVED = 'R', 'Archived'
    DRAFT = 'F', 'Draft'
    PUBLISHED = 'B', 'Published'
    SCHEDULED = 'S', 'Scheduled'
    EXPIRED = 'E', 'Expired'
    CANCELLED = 'C', 'Cancelled'
    COMPLETED = 'M', 'Completed'
    IN_PROGRESS = 'G', 'In Progress'
    ON_HOLD = 'H', 'On Hold'
    PAUSED = 'U', 'Paused'
    RESUMED = 'V', 'Resumed'
    REJECTED = 'J', 'Rejected'
    APPROVED = 'K', 'Approved'
    SUBMITTED = 'L', 'Submitted'
    REVIEWED = 'N', 'Reviewed'
    FEEDBACK = 'O', 'Feedback'
    CLOSED = 'Q', 'Closed'
    OPEN = 'W', 'Open'
    NEW = 'X', 'New'
    UPDATED = 'Y', 'Updated'
    DELETED = 'Z', 'Deleted'
    RESTORED = '1', 'Restored'
    CLONED = '2', 'Cloned'
    MOVED = '3', 'Moved'
    COPIED = '4', 'Copied'
    LOCKED = '5', 'Locked'
