# Generated by Django 3.2.25 on 2025-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='corporate',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
