# Generated by Django 3.2.25 on 2025-07-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_notification_options_and_more'),
        ('OrgAuth', '0002_auto_20250728_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.role'),
        ),
    ]
