# Generated by Django 3.2.25 on 2025-07-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0003_corporateuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='is_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
