# Generated by Django 3.2.25 on 2025-07-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0004_corporate_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
