# Generated by Django 3.2.25 on 2025-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0005_corporate_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='company_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='tax_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
