# Generated by Django 3.2.25 on 2025-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0006_auto_20250829_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='logo',
            field=models.ImageField(upload_to='quidpath_backend/media/corporates/logos/'),
        ),
    ]
