# Generated by Django 3.2.25 on 2025-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0007_alter_corporate_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='logo',
            field=models.ImageField(upload_to='corporates/logos/'),
        ),
    ]
