# Generated by Django 3.2.25 on 2026-02-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0002_corporatesubscription'),
        ('OrgAuth', '0008_alter_corporate_logo'),
    ]

    operations = [
    ]
