# Generated by Django 3.2.25 on 2026-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0009_merge_20260209_1215'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='corporatesubscription',
            name='corporate_s_corpora_idx',
        ),
        migrations.RemoveIndex(
            model_name='corporatesubscription',
            name='corporate_s_billing_idx',
        ),
        migrations.RemoveIndex(
            model_name='corporatesubscription',
            name='corporate_s_end_dat_idx',
        ),
        migrations.AddIndex(
            model_name='corporatesubscription',
            index=models.Index(fields=['corporate_id', 'status'], name='corporate_s_corpora_c72196_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatesubscription',
            index=models.Index(fields=['billing_subscription_id'], name='corporate_s_billing_5d2690_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatesubscription',
            index=models.Index(fields=['end_date'], name='corporate_s_end_dat_dda2b7_idx'),
        ),
    ]
