# Generated by Django 4.2.29 on 2026-04-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0010_auto_20260224_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporateSubscription',
        ),
    ]
