# Generated by Django 4.2.30 on 2026-04-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0010_add_document_template_model'),
        ('OrgAuth', '0011_delete_corporatesubscription'),
    ]

    operations = [
    ]
