# Generated by Django 4.2.30 on 2026-04-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0012_merge_20260408_0937'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttemplate',
            name='unique_corporate_document_type',
        ),
        migrations.RenameIndex(
            model_name='documenttemplate',
            new_name='document_te_corpora_600b2e_idx',
            old_name='document_te_corpora_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('corporate', 'document_type')},
        ),
    ]
