# Generated by Django 3.2.25 on 2025-09-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_alter_account_account_type'),
        ('Banking', '0002_bankaccount_accounting_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='accounting_account',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ledger_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='Accounting.account'),
        ),
    ]
