# Generated by Django 4.2.30 on 2026-04-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0003_auto_20250923_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_reconciliations', to='Banking.bankaccount'),
        ),
    ]
