# Generated by Django 5.2.4 on 2025-07-21 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_customuser_last_otp_sent_at_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ('Notification Type',),
                'verbose_name_plural': ('Notification Types',),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': ('Organisation',),
                'verbose_name_plural': ('Organisations',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ('State',),
                'verbose_name_plural': ('States',),
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('simple_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': ('Transaction Type',),
                'verbose_name_plural': ('Transaction Types',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('destination', models.CharField(max_length=255)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Authentication.notificationtype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Authentication.state')),
            ],
            options={
                'verbose_name': ('Notification',),
                'verbose_name_plural': ('Notifications',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('message', models.TextField(blank=True, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notification_response', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Authentication.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Authentication.transactiontype')),
            ],
            options={
                'verbose_name': ('Transaction',),
                'verbose_name_plural': ('Transactions',),
            },
        ),
    ]
