# Generated by Django 5.2.4 on 2025-07-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_notificationtype_organisation_state_transactiontype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificationtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={},
        ),
    ]
