# Generated by Django 3.2.25 on 2025-07-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
