# Generated by Django 3.2.25 on 2025-07-31 09:36

import Authentication.models.forgotPassword
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20250728_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=Authentication.models.forgotPassword.default_expiry)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
