# Generated by Django 3.2.25 on 2026-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_notification_is_read_corporate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
