# Generated by Django 3.2.25 on 2026-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_alter_notificationtype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
