# Generated by Django 3.2.25 on 2026-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_customuser_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
