# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0010_alter_customuser_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codename", models.CharField(help_text="e.g. accounting.view, accounting.invoices", max_length=100, unique=True)),
                ("module_slug", models.CharField(db_index=True, help_text="e.g. accounting, banking", max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(help_text="Frontend path e.g. /accounting", max_length=255)),
                ("icon_slug", models.CharField(blank=True, help_text="MUI icon name for frontend", max_length=50)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name="children", to="Authentication.modulepermission")),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="module_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modules/menu items this role can access",
                related_name="roles",
                to="Authentication.modulepermission",
            ),
        ),
    ]
