# Generated by Django 5.2.4

from django.db import migrations


def bootstrap_module_permissions(apps, schema_editor):
    ModulePermission = apps.get_model("Authentication", "ModulePermission")
    Role = apps.get_model("Authentication", "Role")

    modules = [
        # (codename, module_slug, name, path, icon_slug, parent_codename, sort_order)
        ("dashboard", "dashboard", "Overview", "/dashboard", "dashboard", None, 0),
        ("accounting", "accounting", "Accounting", "/accounting", "account_balance", None, 10),
        ("accounting.invoices", "accounting", "Invoices", "/accounting/invoices", "", "accounting", 0),
        ("accounting.expenses", "accounting", "Expenses", "/accounting/expenses", "", "accounting", 1),
        ("accounting.reports", "accounting", "Reports", "/accounting/reports", "", "accounting", 2),
        ("accounting.journals", "accounting", "Journal Entries", "/accounting/journals", "", "accounting", 3),
        ("inventory", "inventory", "Inventory", "/inventory", "inventory_2", None, 20),
        ("pos", "pos", "Point of Sale", "/pos", "point_of_sale", None, 30),
        ("crm", "crm", "CRM", "/crm", "people_alt", None, 40),
        ("hrm", "hrm", "HR Management", "/hrm", "badge", None, 50),
        ("projects", "projects", "Projects", "/projects", "folder_open", None, 60),
    ]
    created = {}
    for codename, module_slug, name, path, icon_slug, parent_codename, sort_order in modules:
        parent = created.get(parent_codename) if parent_codename else None
        obj, _ = ModulePermission.objects.get_or_create(
            codename=codename,
            defaults={
                "module_slug": module_slug,
                "name": name,
                "path": path,
                "icon_slug": icon_slug or "",
                "parent": parent,
                "sort_order": sort_order,
            },
        )
        created[codename] = obj

    # SUPERADMIN, ADMIN, ACCOUNTANT, MANAGER: all modules. USER, VIEWER: dashboard + accounting (and children).
    all_perms = list(ModulePermission.objects.all())
    accounting_perm = ModulePermission.objects.filter(codename="accounting").first()
    accounting_children = list(ModulePermission.objects.filter(parent=accounting_perm)) if accounting_perm else []
    dashboard_perm = ModulePermission.objects.filter(codename="dashboard").first()
    limited_perms = [dashboard_perm, accounting_perm] + accounting_children
    limited_perms = [p for p in limited_perms if p]

    for role_name in ["SUPERADMIN", "ADMIN", "ACCOUNTANT", "MANAGER"]:
        role = Role.objects.filter(name=role_name).first()
        if role:
            role.module_permissions.set(all_perms)

    for role_name in ["USER", "VIEWER"]:
        role = Role.objects.filter(name=role_name).first()
        if role:
            role.module_permissions.set(limited_perms)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0011_modulepermission_and_role_module_permissions"),
    ]

    operations = [
        migrations.RunPython(bootstrap_module_permissions, noop),
    ]
