# Generated by Django 4.2.29 on 2026-04-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0011_delete_corporatesubscription'),
        ('Authentication', '0014_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='corporate',
            field=models.ForeignKey(blank=True, help_text='If set, this role belongs to a specific corporate. If null, it is a system-wide role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='OrgAuth.corporate'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'corporate')},
        ),
    ]
