# Generated by Django 3.2.25 on 2025-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('INVOICED', 'INVOICED'), ('CONFIRMED', 'CONFIRMED'), ('RECEIVED', 'RECEIVED'), ('PARTIALLY_RECEIVED', 'PARTIALLY RECEIVED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=255),
        ),
    ]
