# Generated by Django 3.2.25 on 2025-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_auto_20250822_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('PAID', 'PAID'), ('PARTIALLY_PAID', 'PARTIALLY PAID'), ('OVERDUE', 'OVERDUE'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('INVOICED', 'INVOICED'), ('REJECTED', 'REJECTED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('INVOICED', 'INVOICED'), ('CONFIRMED', 'CONFIRMED'), ('RECEIVED', 'RECEIVED'), ('PARTIALLY_RECEIVED', 'PARTIALLY RECEIVED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('INVOICED', 'INVOICED'), ('REJECTED', 'REJECTED')], default='DRAFT', max_length=255),
        ),
    ]
