# Generated by Django 3.2.25 on 2025-09-05 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0008_alter_corporate_logo'),
        ('Accounting', '0003_auto_20250827_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('COST_OF_GOODS_SOLD', 'Cost of Goods Sold')], max_length=20)),
                ('sub_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgAuth.corporate')),
            ],
            options={
                'db_table': 'account',
                'unique_together': {('corporate', 'code')},
            },
        ),
    ]
