# Generated by Django 3.2.25 on 2025-09-05 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'account_type',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.CreateModel(
            name='AccountSubType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='Accounting.accounttype')),
            ],
            options={
                'db_table': 'account_sub_type',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.accountsubtype'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.accounttype'),
        ),
    ]
