# Generated by Django 3.2.25 on 2025-09-08 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0008_alter_corporate_logo'),
        ('Accounting', '0006_journalentry_journalentryline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('PROFIT_LOSS', 'Profit and Loss'), ('BALANCE_SHEET', 'Balance Sheet'), ('CASH_FLOW', 'Cash Flow'), ('INCOME_STATEMENT', 'Income Statement')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgAuth.corporate')),
            ],
            options={
                'db_table': 'financial_report',
            },
        ),
    ]
