# Generated by Django 3.2.25 on 2025-09-12 10:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0008_alter_corporate_logo'),
        ('Accounting', '0007_financialreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_receivable', to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='OrgAuth.corporateuser'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proformainvoiceline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='OrgAuth.corporate'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_tax_rates', to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_tax_rates', to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills_as_payable', to='Accounting.account'),
        ),
        migrations.AddField(
            model_name='vendorbillline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.accounttype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='OrgAuth.corporate'),
        ),
        migrations.AlterField(
            model_name='accountsubtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='OrgAuth.corporate'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='OrgAuth.corporate'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('corporate', 'code'), ('corporate', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='accountsubtype',
            unique_together={('account_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together={('corporate', 'name')},
        ),
        migrations.AlterModelTable(
            name='taxrate',
            table='tax_rate',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('OPERATING', 'Operating Expense'), ('ADMINISTRATIVE', 'Administrative Expense'), ('SELLING', 'Selling Expense'), ('FINANCIAL', 'Financial Expense'), ('OTHER', 'Other Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='OrgAuth.corporate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OrgAuth.corporateuser')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='Accounting.account')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounting.journalentry')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payments', to='Accounting.account')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Accounting.taxrate')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='Accounting.vendor')),
            ],
            options={
                'db_table': 'expense',
                'unique_together': {('corporate', 'reference')},
            },
        ),
    ]
