# Generated by Django 3.2.25 on 2025-11-06 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0010_add_payment_fields_and_new_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='Accounting_corp_audit_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='Accounting_user_audit_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='Accounting_action_audit_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='Accounting_content_audit_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentattachment',
            name='Accounting_content_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentattachment',
            name='Accounting_corp_attach_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='Accounting_corp_sku_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='Accounting_corp_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoices',
            name='Accounting_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoices',
            name='Accounting_corp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoices',
            name='Accounting_pay_ref_idx',
        ),
        migrations.RemoveIndex(
            model_name='recurringtransaction',
            name='Accounting_corp_recur_idx',
        ),
        migrations.RemoveIndex(
            model_name='recurringtransaction',
            name='Accounting_next_recur_idx',
        ),
        migrations.RemoveIndex(
            model_name='recurringtransaction',
            name='Accounting_type_recur_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='Accounting_corp_mov_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='Accounting_item_mov_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='Accounting_wh_mov_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='Accounting_status_mov_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['corporate', 'created_at'], name='Accounting__corpora_c8ea09_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='Accounting__user_id_4df52f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'created_at'], name='Accounting__action__719519_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='Accounting__content_8fc8db_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='Accounting__content_52d528_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['corporate', 'created_at'], name='Accounting__corpora_1c6a42_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['corporate', 'sku'], name='Accounting__corpora_6bc8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['corporate', 'is_active'], name='Accounting__corpora_757b18_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['payment_status'], name='Accounting__payment_7b1497_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['corporate', 'date'], name='Accounting__corpora_2a526c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['payment_reference'], name='Accounting__payment_233367_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['corporate', 'status'], name='Accounting__corpora_400f85_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['next_run_at', 'status'], name='Accounting__next_ru_d3eb10_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='Accounting__transac_3ca162_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['corporate', 'movement_date'], name='Accounting__corpora_a11e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'movement_date'], name='Accounting__item_id_ea5b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'movement_date'], name='Accounting__warehou_3279bb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['status', 'movement_date'], name='Accounting__status_30e808_idx'),
        ),
    ]
