# Generated by Django 4.2.29 on 2026-04-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAuth', '0011_delete_corporatesubscription'),
        ('Accounting', '0011_auto_20251106_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='drafted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_invoices', to='OrgAuth.corporateuser'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='drafted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_proforma_invoices', to='OrgAuth.corporateuser'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='drafted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_purchase_orders', to='OrgAuth.corporateuser'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='drafted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_quotations', to='OrgAuth.corporateuser'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='drafted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_vendor_bills', to='OrgAuth.corporateuser'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('INVOICED', 'INVOICED'), ('REJECTED', 'REJECTED')], db_index=True, default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('INVOICED', 'INVOICED'), ('CONFIRMED', 'CONFIRMED'), ('RECEIVED', 'RECEIVED'), ('PARTIALLY_RECEIVED', 'PARTIALLY RECEIVED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('INVOICED', 'INVOICED'), ('REJECTED', 'REJECTED')], db_index=True, default='DRAFT', max_length=255),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['status'], name='Accounting__status_46c500_idx'),
        ),
    ]
