# Generated by Django 4.2.29 on 2026-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0013_add_petty_cash_and_bank_reconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashfund',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
