# Generated by Django 4.2.29 on 2026-04-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0014_alter_pettycashfund_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='Accounting.taxrate'),
        ),
        migrations.AlterField(
            model_name='proformainvoiceline',
            name='taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoice_lines', to='Accounting.taxrate'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_lines', to='Accounting.taxrate'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='Accounting.taxrate'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bill_lines', to='Accounting.taxrate'),
        ),
    ]
