# Generated by Django 4.2.29 on 2026-04-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0015_alter_invoiceline_taxable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='fob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='ship_via',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='fob',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='ship_via',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='fob',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ship_via',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='fob',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ship_via',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
