name: Build & Push Django Backend

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: bethwelkimutai/quidpath-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Server via SSM
        id: ssm-deploy
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-03491863fe1f5abce \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying latest Django backend" \
            --parameters '{
              "commands": [
                "cd /home/ubuntu/quidpath-erp-backend || { echo Failed to cd; exit 1; }",
                "sudo docker compose pull backend || { echo Failed to pull image; exit 1; }",
                "sudo docker compose up -d --no-deps backend || { echo Failed to start container; exit 1; }"
              ]
            }' \
            --output text \
            --query 'Command.CommandId')
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
        shell: bash


      - name: Check SSM Command Status
        run: |
          aws ssm wait command-executed \
            --instance-id i-03491863fe1f5abce \
            --command-id ${{ steps.ssm-deploy.outputs.command_id }} \
            --region ${{ secrets.AWS_REGION }}
          echo "Command executed successfully. Details:"
          aws ssm list-command-invocations \
            --command-id ${{ steps.ssm-deploy.outputs.command_id }} \
            --details \
            --region ${{ secrets.AWS_REGION }}